### ISSUE TITLE
RC3 roadmap

### ISSUE THREAD

**Issue by piranna** [NodeOS/NodeOS#317]
Since this is getting delayed too much due to luck of focus and time of everybody (I'm the first guilty here...) and have surfaced some problems in the current project code status, this will be a small remainder tasks list of the current WiP and things to be done to release a gooD RC3 soon-ish and some other WiP towards 1.0 version:

- [ ] code refactor
  - [ ] finish it :-P
  - [ ] add support for Docker and Vagga
  - [ ] add support for WSL
- [ ] GIT client ([nogit](https://github.com/whyleee/nogit) or [nodeos-git](https://github.com/luii/nodeos-git))
- [ ] finish refactor of `nsh`
  - [ ] stabilize its functionality using `coreutils.js`
  - [ ] port to `bash-parser`
  - [ ] replace interpreter for compiler
- [ ] build on WSL
- [ ] improve documentation everywhere
- [ ] create BarebonesOS project from `nodeos-barebones` source code
- [ ] use and configure `prebuild-install` and `buho` on all the projects to have an automated Rolling Release system

Any other missing idea?
