### ISSUE TITLE
Let's build an alpha

### ISSUE THREAD

**Issue by piranna** [NodeOS/NodeOS#37]
I have created a [milestione](https://github.com/NodeOS/NodeOS/issues?milestone=1) so we can start to focus on develop an initial public release. We can discuss here what things should be added. Please maintain the features to the minimal (it's a first release, after all), and just put here what the idea, but develop them in a new issue.
- [x] update & improve documentation
- [x] minimal system
  - [x] ramdisk root filesystem bundle (kernel + node binary packed in a ramdisk image)
  - [x] minit (minimal init for PID 1)
  - [x] ~~_boot_ module (for starting dhcp/getty via asgard)~~
  - [x] ~~asgard (to run as PID 2)~~ Using [forever-starter](https://github.com/nodejitsu/forever/pull/600) instead
    - [x] _getty_ replacement written in Node.js (for binding to `/dev/console`)
  - [x] multiuser ([logon](https://github.com/piranna/logon) + filesystem permissions)
  - [x] OverlayFS-based root filesystem
    - [x] read-only ramdisk root filesystem
  - [x] network support
    - [x] enable/disable network interfaces
    - [x] static IPs
  - [x] command line tools
    - [x] npm
    - [x] nsh update
    - [x] [text editor](https://github.com/NodeOS/NodeOS/issues/66)
    - [ ] [git client](https://github.com/NodeOS/NodeOS/issues/67), maybe we can use [gitlet](https://github.com/maryrosecook/gitlet)
  - [x] The Big Red Button (script to build everything with just one command)
    - [x] generate images for all platforms at once
    - [x] prepare an empty file system
    - [x] install all system packages (download?)
  - [x] different UIDs & GIDs for each user home folder
    - [x] DevicesManager (`/dev` filesystem)
  - [x] `/proc` accesible for everybody
  - [x] [fbdev](https://github.com/Automattic/node-canvas/issues/533)
- [x] Instalable distro
  - [x] Self-contained source code
    - [x] custom, minimal compiled kernel
    - [x] libraries
  - [x] Multiple architectures
    - [x] x86
    - [x] x86_64
  - [x] Multiple platforms
    - [x] ~~Docker~~ Use [Vagga](https://github.com/tailhook/vagga), maybe with Docker compatibility
    - [x] x86 QEmu
    - [x] x86_64 QEmu
  - [x] Run on hardware
    - [x] kernel & initramfs in rootfs images
    - [x] GRUB image (instalable by hand with `dd` and/or `cp`/script)
- [x] no binary executables (only libraries bindings, executables are only Node.js programs)
  - [x] replace `/usr/bin/env` with Javascript alternative (function? NODE_PATH? patched kernel? script with hard-coded she-bang?)

Minor tasks:
- [x] Read kernel arguments from /proc (root and home)
- [x] Allow logon to create new users
- [x] Move root home to usersfs
- [x] Make usersfs ownership to root
- [x] Mount rootfs as read-only

**Comment by piranna** [comment]
NodeOS now cross-compile and run on QEmu x86 32 & 64 bits ^^ Code is on master, needs some fix-ups for launching and testing (they are currently focused only for 32 bits) but are minor ones :-)

**Comment by lite20** [comment]
Only two more things to go!
